CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255),
    username VARCHAR(255)
);

CREATE TABLE users_roles
(
    role_id BIGINT NOT NULL REFERENCES roles (id),
    user_id BIGINT NOT NULL REFERENCES users (id),
    PRIMARY KEY (role_id, user_id)
);

-- Índice para buscar usuarios por nombre de forma rápida
CREATE INDEX idx_users_username ON users (username);

INSERT INTO roles (name) VALUES ('USER');
INSERT INTO roles (name) VALUES ('ADMIN');

INSERT INTO users (username, password) VALUES ('usuario_normal', '$2a$12$41m/m45W1h6fCB.fwziG2enauLiX8gaaj5Dk3HtIcGjq8x9zs6b2q');
INSERT INTO users (username, password) VALUES ('usuario_admin', '$2a$12$41m/m45W1h6fCB.fwziG2enauLiX8gaaj5Dk3HtIcGjq8x9zs6b2q');

INSERT INTO users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 2);
