spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bootcamp_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update