spring:
  application:
    name: flight-service
  security:
    user:
      name: admin
      password: bootcamp2026
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    open-in-view: false