spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:airline_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
    # Muy importante si usas Spring Security:
  sql:
     init:
       mode: always